### ISSUE TITLE
ART-Status response-loop until Status=100

### ISSUE THREAD

**Issue by hersches** [WooYellowCube/wooyellowcube#4]
ART CreateMasterData

The Status-loop like for CustomerDeliveryOrders(WAB) has to be added to the ART-Transfer too - 
see line #1034 in the index.php
                    // Update the order **and products** only when we got 100 StatusCode
                    if($response->getStatusCode() == 100){

If Status is < 100, the ART-message is still processing and the modul-icon should be orange in the wc.products dialog and in the activity-log from module wooyellowcube. The SOAP-response-status-text "file received" is only a temporary "transmitted"-status not a "accepted"-status.

**Comment by michaelambass** [comment]
Fixed on V2.3R2
